Using gpu device 2: GeForce GTX TITAN X (CNMeM is enabled with initial size: 95.0% of memory, cuDNN not available)
Traceback (most recent call last):
  File "/home/s1045064/dissertation/repo-diss/sentence-classification/three.py", line 581, in <module>
    non_static=True)
  File "/home/s1045064/dissertation/repo-diss/sentence-classification/three.py", line 325, in train_conv_net
    cost_epoch = train_model(minibatch_index)
  File "/home/s1045064/dissertation/venv/lib/python2.7/site-packages/theano/compile/function_module.py", line 871, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/s1045064/dissertation/venv/lib/python2.7/site-packages/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/s1045064/dissertation/venv/lib/python2.7/site-packages/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
ValueError: dimension mismatch in args to gemm (200,675)x(450,3)->(200,3)
Apply node that caused the error: GpuDot22(GpuJoin.0, GpuElemwise{mul,no_inplace}.0)
Toposort index: 307
Inputs types: [CudaNdarrayType(float32, matrix), CudaNdarrayType(float32, matrix)]
Inputs shapes: [(200, 675), (450, 3)]
Inputs strides: [(675, 1), (3, 1)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[GpuCrossentropySoftmaxArgmax1HotWithBias(GpuDot22.0, b, GpuElemwise{Identity,no_inplace}.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
